[package]
name = "agentverse-demo-tools"
version.workspace = true
edition.workspace = true
rust-version.workspace = true

[dependencies]
agentverse    = { path = "../../avs-core" }
async-trait   = { workspace = true }
chrono        = { workspace = true }
schemars      = { workspace = true }
serde         = { workspace = true, features = ["derive"] }
serde_json    = { workspace = true }

[dev-dependencies]
tokio = { workspace = true, features = ["rt-multi-thread", "macros"] }
