[package]
name = "agentverse-router"
version.workspace = true
license.workspace = true
edition.workspace = true
rust-version.workspace = true

[dependencies]
agentverse = { path = "../avs-core" }
agentverse-guardrails = { path = "../avs-guardrails" }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
tracing = { workspace = true }

[dev-dependencies]
tokio = { workspace = true, features = ["rt", "macros"] }
async-trait = { workspace = true }
