[package]
name = "example-anthropic-react"
version.workspace = true
edition.workspace = true
rust-version.workspace = true

[dependencies]
agentverse = { path = "../../avs-core" }
agentverse-agent = { path = "../../avs-agent" }
agentverse-logging = { path = "../../avs-logging" }
agentverse-memory = { path = "../../avs-memory" }
agentverse-session = { path = "../../avs-session" }
agentverse-strategy = { path = "../../avs-strategy" }
agentverse-tools = { path = "../../avs-tools" }
tokio.workspace = true
tracing.workspace = true
