[package]
name = "example-web-search-agent"
version.workspace = true
edition.workspace = true

[dependencies]
agentverse = { path = "../../avs-core" }
agentverse-memory = { path = "../../avs-memory" }
agentverse-plan = { path = "../../avs-plan" }
agentverse-tools = { path = "../../avs-tools" }
async-trait.workspace = true
tokio.workspace = true
