[package]
name = "agentverse-server"
version.workspace = true
edition.workspace = true
rust-version.workspace = true

[[bin]]
name = "agentverse"
path = "src/main.rs"



[dependencies]
agentverse = { path = "../avs-core" }
agentverse-session = { path = "../avs-session" }
agentverse-react = { path = "../avs-react" }
agentverse-plan = { path = "../avs-plan" }
agentverse-guardrails = { path = "../avs-guardrails" }
agentverse-integration = { path = "../avs-integration" }
agentverse-tools = { path = "../avs-tools" }
agentverse-memory = { path = "../avs-memory" }
agentverse-memory-lancedb = { path = "../avs-memory-lancedb" }
agentverse-logging = { path = "../avs-logging" }
axum = { workspace = true, features = ["macros"] }
serde.workspace = true
serde_json.workspace = true
tokio.workspace = true
clap.workspace = true
uuid.workspace = true
tracing.workspace = true
serde_yaml.workspace = true
utoipa = { workspace = true }
utoipa-swagger-ui = { workspace = true }
tower = { workspace = true }
tower-http = { workspace = true }
reqwest = { workspace = true }

[dev-dependencies]
httpmock = { workspace = true }
