[package]
name = "agentverse-integration"
version.workspace = true
edition.workspace = true

[dependencies]
agentverse = { path = "../avs-core" }
async-trait.workspace = true
axum.workspace = true
serde.workspace = true
serde_json.workspace = true
tokio.workspace = true
tracing.workspace = true
thiserror.workspace = true
