[package]
name = "example-react-calculator"
version.workspace = true
edition.workspace = true

[dependencies]
agentverse = { path = "../../avs-core" }
agentverse-logging = { path = "../../avs-logging" }
agentverse-memory = { path = "../../avs-memory" }
agentverse-react = { path = "../../avs-react" }
agentverse-tools = { path = "../../avs-tools" }
tokio.workspace = true
tracing.workspace = true
